connections:
  chiplet_0:
    - [0, 1]
    - [0, 10]
  chiplet_1:
    - [1, 0]
    - [1, 2]
    - [1, 11]
  chiplet_2:
    - [2, 1]
    - [2, 3]
    - [2, 12]
  chiplet_3:
    - [3, 2]
    - [3, 4]
    - [3, 13]
  chiplet_4:
    - [4, 3]
    - [4, 5]
    - [4, 14]
  chiplet_5:
    - [5, 4]
    - [5, 6]
    - [5, 15]
  chiplet_6:
    - [6, 5]
    - [6, 7]
    - [6, 16]
  chiplet_7:
    - [7, 6]
    - [7, 8]
    - [7, 17]
  chiplet_8:
    - [8, 7]
    - [8, 9]
    - [8, 18]
  chiplet_9:
    - [9, 8]
    - [9, 19]
  chiplet_10:
    - [10, 0]
    - [10, 11]
    - [10, 20]
  chiplet_11:
    - [11, 1]
    - [11, 10]
    - [11, 12]
    - [11, 21]
  chiplet_12:
    - [12, 2]
    - [12, 11]
    - [12, 13]
    - [12, 22]
  chiplet_13:
    - [13, 3]
    - [13, 12]
    - [13, 14]
    - [13, 23]
  chiplet_14:
    - [14, 4]
    - [14, 13]
    - [14, 15]
    - [14, 24]
  chiplet_15:
    - [15, 5]
    - [15, 14]
    - [15, 16]
    - [15, 25]
  chiplet_16:
    - [16, 6]
    - [16, 15]
    - [16, 17]
    - [16, 26]
  chiplet_17:
    - [17, 7]
    - [17, 16]
    - [17, 18]
    - [17, 27]
  chiplet_18:
    - [18, 8]
    - [18, 17]
    - [18, 19]
    - [18, 28]
  chiplet_19:
    - [19, 9]
    - [19, 18]
    - [19, 29]
  chiplet_20:
    - [20, 10]
    - [20, 21]
    - [20, 30]
  chiplet_21:
    - [21, 11]
    - [21, 20]
    - [21, 22]
    - [21, 31]
  chiplet_22:
    - [22, 12]
    - [22, 21]
    - [22, 23]
    - [22, 32]
  chiplet_23:
    - [23, 13]
    - [23, 22]
    - [23, 24]
    - [23, 33]
  chiplet_24:
    - [24, 14]
    - [24, 23]
    - [24, 25]
    - [24, 34]
  chiplet_25:
    - [25, 15]
    - [25, 24]
    - [25, 26]
    - [25, 35]
  chiplet_26:
    - [26, 16]
    - [26, 25]
    - [26, 27]
    - [26, 36]
  chiplet_27:
    - [27, 17]
    - [27, 26]
    - [27, 28]
    - [27, 37]
  chiplet_28:
    - [28, 18]
    - [28, 27]
    - [28, 29]
    - [28, 38]
  chiplet_29:
    - [29, 19]
    - [29, 28]
    - [29, 39]
  chiplet_30:
    - [30, 20]
    - [30, 31]
    - [30, 40]
  chiplet_31:
    - [31, 21]
    - [31, 30]
    - [31, 32]
    - [31, 41]
  chiplet_32:
    - [32, 22]
    - [32, 31]
    - [32, 33]
    - [32, 42]
  chiplet_33:
    - [33, 23]
    - [33, 32]
    - [33, 34]
    - [33, 43]
  chiplet_34:
    - [34, 24]
    - [34, 33]
    - [34, 35]
    - [34, 44]
  chiplet_35:
    - [35, 25]
    - [35, 34]
    - [35, 36]
    - [35, 45]
  chiplet_36:
    - [36, 26]
    - [36, 35]
    - [36, 37]
    - [36, 46]
  chiplet_37:
    - [37, 27]
    - [37, 36]
    - [37, 38]
    - [37, 47]
  chiplet_38:
    - [38, 28]
    - [38, 37]
    - [38, 39]
    - [38, 48]
  chiplet_39:
    - [39, 29]
    - [39, 38]
    - [39, 49]
  chiplet_40:
    - [40, 30]
    - [40, 41]
    - [40, 50]
  chiplet_41:
    - [41, 31]
    - [41, 40]
    - [41, 42]
    - [41, 51]
  chiplet_42:
    - [42, 32]
    - [42, 41]
    - [42, 43]
    - [42, 52]
  chiplet_43:
    - [43, 33]
    - [43, 42]
    - [43, 44]
    - [43, 53]
  chiplet_44:
    - [44, 34]
    - [44, 43]
    - [44, 45]
    - [44, 54]
  chiplet_45:
    - [45, 35]
    - [45, 44]
    - [45, 46]
    - [45, 55]
  chiplet_46:
    - [46, 36]
    - [46, 45]
    - [46, 47]
    - [46, 56]
  chiplet_47:
    - [47, 37]
    - [47, 46]
    - [47, 48]
    - [47, 57]
  chiplet_48:
    - [48, 38]
    - [48, 47]
    - [48, 49]
    - [48, 58]
  chiplet_49:
    - [49, 39]
    - [49, 48]
    - [49, 59]
  chiplet_50:
    - [50, 40]
    - [50, 51]
    - [50, 60]
  chiplet_51:
    - [51, 41]
    - [51, 50]
    - [51, 52]
    - [51, 61]
  chiplet_52:
    - [52, 42]
    - [52, 51]
    - [52, 53]
    - [52, 62]
  chiplet_53:
    - [53, 43]
    - [53, 52]
    - [53, 54]
    - [53, 63]
  chiplet_54:
    - [54, 44]
    - [54, 53]
    - [54, 55]
    - [54, 64]
  chiplet_55:
    - [55, 45]
    - [55, 54]
    - [55, 56]
    - [55, 65]
  chiplet_56:
    - [56, 46]
    - [56, 55]
    - [56, 57]
    - [56, 66]
  chiplet_57:
    - [57, 47]
    - [57, 56]
    - [57, 58]
    - [57, 67]
  chiplet_58:
    - [58, 48]
    - [58, 57]
    - [58, 59]
    - [58, 68]
  chiplet_59:
    - [59, 49]
    - [59, 58]
    - [59, 69]
  chiplet_60:
    - [60, 50]
    - [60, 61]
    - [60, 70]
  chiplet_61:
    - [61, 51]
    - [61, 60]
    - [61, 62]
    - [61, 71]
  chiplet_62:
    - [62, 52]
    - [62, 61]
    - [62, 63]
    - [62, 72]
  chiplet_63:
    - [63, 53]
    - [63, 62]
    - [63, 64]
    - [63, 73]
  chiplet_64:
    - [64, 54]
    - [64, 63]
    - [64, 65]
    - [64, 74]
  chiplet_65:
    - [65, 55]
    - [65, 64]
    - [65, 66]
    - [65, 75]
  chiplet_66:
    - [66, 56]
    - [66, 65]
    - [66, 67]
    - [66, 76]
  chiplet_67:
    - [67, 57]
    - [67, 66]
    - [67, 68]
    - [67, 77]
  chiplet_68:
    - [68, 58]
    - [68, 67]
    - [68, 69]
    - [68, 78]
  chiplet_69:
    - [69, 59]
    - [69, 68]
    - [69, 79]
  chiplet_70:
    - [70, 60]
    - [70, 71]
    - [70, 80]
  chiplet_71:
    - [71, 61]
    - [71, 70]
    - [71, 72]
    - [71, 81]
  chiplet_72:
    - [72, 62]
    - [72, 71]
    - [72, 73]
    - [72, 82]
  chiplet_73:
    - [73, 63]
    - [73, 72]
    - [73, 74]
    - [73, 83]
  chiplet_74:
    - [74, 64]
    - [74, 73]
    - [74, 75]
    - [74, 84]
  chiplet_75:
    - [75, 65]
    - [75, 74]
    - [75, 76]
    - [75, 85]
  chiplet_76:
    - [76, 66]
    - [76, 75]
    - [76, 77]
    - [76, 86]
  chiplet_77:
    - [77, 67]
    - [77, 76]
    - [77, 78]
    - [77, 87]
  chiplet_78:
    - [78, 68]
    - [78, 77]
    - [78, 79]
    - [78, 88]
  chiplet_79:
    - [79, 69]
    - [79, 78]
    - [79, 89]
  chiplet_80:
    - [80, 70]
    - [80, 81]
    - [80, 90]
  chiplet_81:
    - [81, 71]
    - [81, 80]
    - [81, 82]
    - [81, 91]
  chiplet_82:
    - [82, 72]
    - [82, 81]
    - [82, 83]
    - [82, 92]
  chiplet_83:
    - [83, 73]
    - [83, 82]
    - [83, 84]
    - [83, 93]
  chiplet_84:
    - [84, 74]
    - [84, 83]
    - [84, 85]
    - [84, 94]
  chiplet_85:
    - [85, 75]
    - [85, 84]
    - [85, 86]
    - [85, 95]
  chiplet_86:
    - [86, 76]
    - [86, 85]
    - [86, 87]
    - [86, 96]
  chiplet_87:
    - [87, 77]
    - [87, 86]
    - [87, 88]
    - [87, 97]
  chiplet_88:
    - [88, 78]
    - [88, 87]
    - [88, 89]
    - [88, 98]
  chiplet_89:
    - [89, 79]
    - [89, 88]
    - [89, 99]
  chiplet_90:
    - [90, 80]
    - [90, 91]
  chiplet_91:
    - [91, 81]
    - [91, 90]
    - [91, 92]
  chiplet_92:
    - [92, 82]
    - [92, 91]
    - [92, 93]
  chiplet_93:
    - [93, 83]
    - [93, 92]
    - [93, 94]
  chiplet_94:
    - [94, 84]
    - [94, 93]
    - [94, 95]
  chiplet_95:
    - [95, 85]
    - [95, 94]
    - [95, 96]
  chiplet_96:
    - [96, 86]
    - [96, 95]
    - [96, 97]
  chiplet_97:
    - [97, 87]
    - [97, 96]
    - [97, 98]
  chiplet_98:
    - [98, 88]
    - [98, 97]
    - [98, 99]
  chiplet_99:
    - [99, 89]
    - [99, 98]
